### ISSUE TITLE
Storing behaviour

### ISSUE THREAD

**Issue by rsedykh** [uploadcare/uploadcare-ruby#155]
We've recently updated storing behaviour, which affects only new users — https://uploadcare.com/docs/changelog/#2024-02-12 (read changelog entry and follow the documentation link).

What should be done:
* Use store = auto in examples, unless it's an example of forced false or true behaviour.
* Make sure that if storing behaviour is explained (in the documentation or in the code comments), it's explained about all three options: true, false, and auto (sometimes auto is skipped entirely). Provide links to documentation/refs if necessary.

**Comment by vipulnsward** [comment]
Looks like we kind of already started doing "auto", even before https://uploadcare.com/docs/changelog/#2024-02-12 😃

Ref: https://github.com/uploadcare/uploadcare-ruby/blob/10efe72c8d76afcb1d0e8dc4ec09339cf640476b/lib/uploadcare/param/upload/upload_params_generator.rb#L26-L26

This was since https://github.com/uploadcare/uploadcare-ruby/commit/88dfed6c94de38323b41b334c5c796950a4ea97b#diff-d619384f20c0068d24701b1f307ba2daa84c09aacb7d3ce309ee21263c823bbb 

I am looking around now and changing in the examples.
